# Template config, need to change dump_dir, data.root_dir and tokenizer.path

dump_dir: /fsx-checkpoints/new/lingua_dumps/test
name: "scaling_law"
probe_freq: 100
seed: 777
optim:
    lr: 3e-4
    warmup: 2000
    lr_min_ratio: 0.000001
    clip: 10.0

distributed:
    fsdp_type: full_shard
    compile: true
    model_dtype: bf16
    matmul_allow_tf32: false
    selective_activation_checkpointing: false
    tp_size: 1

#total_batch_size = batch_size(32) * grad_acc(1) = 32      
#tokens_per_step = seq_len(2048) * total_batch_size(32) * NGPUs(32) = 2^11 * 2^5 *2^5 = 2^21 = 2M
 
data:
    root_dir: /data/home/feiyang/feiyang/trlingua/lingua/setup/data/
    sources:
        fineweb_edu_10bt_shuffled: 1.0
    batch_size: 32
    prefetch_size: 64
    seq_len: 2048
    n_views: 2
    load_async: true
    tokenizer:
        name: sp
        path: /data/home/feiyang/.llama/checkpoints/Llama-2-7b/tokenizer.model

profiling:
    run: true

checkpoint:
    dump:
        every: 10000
        keep: 5
    eval:
        every: 100
        keep: 1

logging:
    freq: 10

eval:
    generator:
        max_tokens: 8192
        dtype: bf16
        temperature: 1.0
        top_p: 0.95
    harness:
        tasks:
            - hellaswag
            - piqa
            - task: nq_open
              num_fewshot: 5
