include: ["apps/main/configs/scaling_law/base.yaml"]

#total_num_tokens = steps (10_000) * total_tokens_per_step (1M) = 10B
#NOTE: total_tokens_per_step will be affected by number of GPUs. Adjust #steps based on your number of GPUs either here or in cmdline.
steps: 10_000

model:
    dim: 576
    n_layers: 7
    n_heads: 9
